[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    schreibfaul1/ESP32-Audio@^0.9.0
    lovyan03/LovyanGFX@^1.1.0
build_flags =
    -D CORE_DEBUG_LEVEL=0
